
spring:
  main:
    banner-mode: false

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop #controls the behavior of the database schema generation.
    show-sql: true
    properties:
      hibernate:
        format_sql: true # the SQL output in a more readable manner with proper indentation
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
